apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
  namespace: test
  labels:
    app: test
spec:
  # nodeSelector:
  #   gpu: nvidia
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: test-py
    image: python:3.9-slim
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits: 
        cpu: "3"
        memory: "6Gi"
    volumeMounts:
    # - name: config
    #   mountPath: "/etc/config"
      - name: smb
        mountPath: "/source/local_values.py"
        subPath: "ttrade/local_values.py"
        readOnly: true
      - name: azsmb
        mountPath: "/data/raw"
        subPath: "ttrade/raw"
      - name: smb
        mountPath: "/data/data"
        subPath: "ttrade/data/241212"
  volumes:
    # - name: datadir
    #   hostPath:
    #     path: /DATA1/ttrade
    #     type: DirectoryOrCreate
    - name: smb
      persistentVolumeClaim:
        claimName: pvc-smb
    - name: azsmb
      persistentVolumeClaim:
        claimName: pvc-azsmb
