apiVersion: v1
kind: Pod
metadata:
  name: data-transform
  namespace: ttrade
  labels:
    app: data-transform
spec:
  nodeSelector:
    gpu: nvidia
  containers:
  - name: data-transform
    image: dogring/tt-transform:1.2
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "500m"
        memory: "1.5Gi"
      limits: 
        cpu: "1"
        memory: "2Gi"
    volumeMounts:
      - name: smb
        mountPath: "/source/local_values.py"
        subPath: "ttrade/local_values.py"
        readOnly: true
      - name: datadir
        mountPath: "/data/raw"
        subPath: "raw"
        readOnly: true
      - name: datadir
        mountPath: "/data/data"
        subPath: "data"
      - name: config
        mountPath: "/etc/config"
        readOnly: true
  volumes:
    - name: datadir
      hostPath:
        path: /DATA1/ttrade
        type: DirectoryOrCreate
    - name: smb
      persistentVolumeClaim:
        claimName: pvc-smb
    - name: config
      configMap:
        name: data-config
  restartPolicy: Never