apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
  namespace: test
  labels:
    app: test
spec:
  nodeSelector:
    gpu: nvidia
  containers:
  - name: test-py
    image: dogring/tt-transform
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: smb
        mountPath: "/source/local_values.py"
        subPath: "ttrade/local_values.py"
        readOnly: true
      - name: datadir
        mountPath: "/data/raw"
        subPath: "raw"
        readOnly: true
      - name: datadir
        mountPath: "/data/data"
        subPath: "data"
  volumes:
    - name: datadir
      hostPath:
        path: /DATA1/ttrade
        type: DirectoryOrCreate
    - name: smb
      persistentVolumeClaim:
        claimName: pvc-smb