apiVersion: batch/v1
kind: CronJob
metadata:
  name: transform-data
  namespace: ttrade
spec:
  schedule: "0 1 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: data-smb
            image: dogring/tt-transform:1.0
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: "500m"
                memory: "1.5Gi"
              limits: 
                cpu: "1"
                memory: "2Gi"
            env:
              - name: FILE_PATHS
                value: "/data/data/"
              - name: SCALER_PATH
                value: "/data/data/scaler/"
            volumeMounts:
              - name: smb
                mountPath: "/source/local_values.py"
                subPath: "ttrade/local_values.py"
                readOnly: true
              - name: smb
                mountPath: "/source/indicators.py"
                subPath: "ttrade/lib/indicators.py"
                readOnly: true
              - name: smb
                mountPath: "/source/data_transform.py"
                subPath: "ttrade/lib/data_transform.py"
                readOnly: true
              - name: azsmb
                mountPath: "/data/raw"
                subPath: "ttrade/raw"
                readOnly: true
              - name: smb
                mountPath: "/data/data"
                subPath: "ttrade/data/241212"
          volumes:
            - name: smb
              persistentVolumeClaim:
                claimName: pvc-smb
            - name: azsmb
              persistentVolumeClaim:
                claimName: pvc-azsmb