apiVersion: batch/v1
kind: CronJob
metadata:
  name: transform-data
  namespace: ttrade
spec:
  schedule: "0 1 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: data-smb
            image: dogring/tt-transform:1.4
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: "500m"
                memory: "1.5Gi"
              limits: 
                cpu: "1"
                memory: "2Gi"
            env:
              - name: FILE_PATHS
                value: "/smb/data/"
              - name: SCALER_PATH
                value: "/data/data/scaler/"
            volumeMounts:
              - name: smb
                mountPath: "/source/local_values.py"
                subPath: "ttrade/local_values.py"
                readOnly: true
              - name: smb
                mountPath: "/data/raw"
                subPath: "ttrade/raw"
                readOnly: true
              - name: smb
                mountPath: "/data/data"
                subPath: "ttrade/data"
              - name: smb-data
                mountPath: "/smb/data"
                subPath: "ttrade/data"
              - name: config
                mountPath: "/etc/config"
                readOnly: true
          volumes:
            - name: smb
              persistentVolumeClaim:
                claimName: pvc-smb
            - name: smb-data
              persistentVolumeClaim:
                claimName: pvc-data-smb
            - name: config
              configMap:
                name: data-config