apiVersion: v1
kind: ConfigMap
metadata:
  name: train-config
  namespace: ttrade
data:
  model.json: |
    {
      "seq_len": 180,
      "pred_len": 8,
      "enc_in": 10,
      "d_model": 96,
      "dropout": 0.2,
      "rnn_type": "lstm",
      "dec_way": "pmf",
      "seg_len": 4,
      "channel_id": 1,
      "revin": true
    }
  dataset.json: |
    {
      "seq_len": 180,
      "pred_len": 8,
      "tickers": ["KRW-BTC","KRW-ETH"],
      "features": ["close", "EMA5", "EMA30", "EMA60", "value", "BW20", "dis20", "Mmt20", "RSI14", "MACD"],
      "target": ["EMA5"]
    }