apiVersion: v1
kind: ConfigMap
metadata:
  name: train-config
  namespace: ttrade
data:
  model.json: |
    {
      "seq_len": 60,
      "pred_len": 10,
      "enc_in": 10,
      "d_model": 64,
      "dropout": 0.2,
      "rnn_type": "lstm",
      "dec_way": "pmf",
      "seg_len": 10,
      "channel_id": 1,
      "revin": true
    }
  dataset.json: |
    {
      "seq_len": 60,
      "pred_len": 10,
      "tickers": ["KRW-BTC","KRW-ETH","KRW-XRP","KRW-ETC"],
      "features": ["close", "EMA5", "EMA30", "EMA60", "value", "BW", "dis", "Mmt", "RSI", "MACD"],
      "target": ["EMA5"]
    }